version: '2.17.3'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER_URL = "redis://redis:6379"
    depends_on:
      - pgdb
      - redis

  celery_worker:
    build: .
    command: celery -A summer worker -l info --pool=solo
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis
  
  celery_beat:
    build: .
    command: celery -A summer beat -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=parser
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ayan2002
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis"

volumes:
  pgdata:



