# Generated by Django 4.1.4 on 2023-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('current', models.FloatField()),
                ('change', models.FloatField()),
                ('percent_change', models.FloatField()),
                ('hayday', models.FloatField()),
                ('lowday', models.FloatField()),
                ('openday', models.FloatField()),
                ('prevclose', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
